.nolist
.include "../m328Pdef.inc"
.list

.equ BUTTON_A = PD7 ; for increasing
.equ BUTTON_B = PD6 ; for decreasing
.def AUX = R16
.ORG 0x0000
INIT:
	LDI AUX, 0b00001111
	OUT DDRD, AUX
	LDI AUX, 0b00000000
	OUT PORTD, AUX
	;NOP
	;LDI AUX, 0X00

OBSERVATOR:
	SBIC PIND, BUTTON_A
	RJMP INCREASING_MODE
	SBIC PIND, BUTTON_B
	RJMP DECREASING_MODE
	RJMP OBSERVATOR

INCREASING_MODE:
	SBIC PIND, BUTTON_A
	RJMP INCREASING_MODE
INCREASING:
	INC AUX
	OUT PORTD, AUX
	RCALL DELAY
	SBIS PIND, BUTTON_B
	RJMP INCREASING
	RJMP DECREASING
DECREASING_MODE:
	SBIC PIND, BUTTON_B
	RJMP DECREASING
DECREASING:
	DEC AUX
	OUT PORTD, AUX
	RCALL DELAY
	SBIS PIND, BUTTON_A
	RJMP DECREASING
	RJMP INCREASING
DELAY:
    LDI R20, 50
L3: LDI R17, 255
L2: LDI R18, 255
L1: DEC R18
    BRNE L1
    DEC R17
    BRNE L2
    DEC R20
    BRNE L3
    RET
